name: Test Jupyter Notebook Environment

on:
  push:
    paths:
      - '**/*.ipynb'  # Trigger only if a .ipynb file is added/modified
  pull_request:
    paths:
      - '**/*.ipynb'  # Trigger only if a .ipynb file is added/modified

jobs:
  test_environment:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Check if env.yml exists (using action)
      - name: Check if env.yml exists
        uses: ./actions/action-check-env.yml

      # Step 3: Create the environment from env.yml (using action)
      - name: Create environment from env.yml
        uses: ./actions/action-create-env.yml

  
